export enum Screens {
  Onboarding = "Onboarding",
  SignUp = "SignUp",
  Explore = "Explore",
  HomePage = "HomePage",
  Basket = "Basket",
  DeliveryAddress = "DeliveryAddress",
  CardDetails = "CardDetails",
  Congratulations = "Congratulations",
  Profile = "Profile",
  Orders = "Orders",
  Favourites = "Favourites",
  ProductDetails = "ProductDetails",
  OrderSuccess = "OrderSuccess",
}
